### ISSUE TITLE
`AVCONTEXT_IO_ERROR` is raised when demuxing a TS video.

### ISSUE THREAD

**Issue by calvin** [janbar/demux-mpegts#1]
Platform: iOS 8.1
Video: H.264/MPEG-4 AVC, 1920 x 1080
Audio: ACC, Mono

The audio is demuxed properly, however, not the video.

```
[DEMUX] dump stream infos for channel 1 PID 1011
  Codec name     : h264
  Language       : 
  Identifier     : 00000000
  FPS scale      : 33367
  FPS rate       : 1000000
  Interlaced     : false
  Height         : 1080
  Width          : 1920
  Aspect         : 1.778
  Channels       : 0
  Sample rate    : 0
  Block align    : 0
  Bit rate       : 0
  Bit per sample : 0

[DEMUX] time 00003.003 : PTS=32699667 Position=3386632
[DEMUX] time 00006.006 : PTS=32969937 Position=6560072
[DEMUX] time 00009.009 : PTS=33240207 Position=9745544
[DEMUX] Do: stopped with status -2
```

The error is raised at https://github.com/janbar/demux-mpegts/blob/61fa66dcb687cf48e3b82c0cfc46f913b2a42382/src/tsDemuxer.cpp#L332, when `av_pos =  10571052` and `av_pkt_size =  188`.
The video in question is supplied to the author's email, j...68@gmail.com on 2015-09-09.

**Comment by janbar** [comment]
Hi, thanks to report.

It is not an issue but the test program doesn't care about the end of the input file and request to read it in a spin loop: https://github.com/janbar/demux-mpegts/blob/61fa66dcb687cf48e3b82c0cfc46f913b2a42382/src/test_demux.cpp#L134 .
At the position 10571052, which is the end of the input file, the demuxer returns awaited error code -2, meaning end of input stream for the case. The generated stream files `stream_1_1011_h264` and `stream_1_1100_aac` are proper and can be read or inspected with adapted player or tool. You could try `mplayer stream_1_1011_h264`.

For a real application using this lib, you could check end of input stream before continue to request more at https://github.com/janbar/demux-mpegts/blob/61fa66dcb687cf48e3b82c0cfc46f913b2a42382/src/test_demux.cpp#L137 , or simply catching this status.

**Comment by calvin** [comment]
Thanks for prompted response :+1:

That's what I have figured out too. But the demuxed video (stream_1_1011_h264) is not readable at this stage. Do you have any idea why?

**Comment by janbar** [comment]
It should be, but with the proper tool like mplayer or vlc which can handle this stream. Often other players need a container. If you cannot read it with one of these tool then send me the demuxed file for testing.
For info today this lib is used by the addon of Kodi (previously XBMC) to support the pvr MythTV and It works well on all supported platforms. Maybe it could be an issue with yours on ios.

**Comment by calvin** [comment]
Thanks for your time. I was using VLC to test out the elementary video and
it turned out VLC cannot play it. Aa you suggested, I tested it with
MPlayet and I was able to play it :)

**Comment by janbar** [comment]
Yes i tried with vlc (2.16) and it cannot manage this stream out of the container. Nothing unusual because PTS data are required to handle the playback. The `test` program is intented to check the parsing and finally it saves flow of streams for debug. You could check how this lib is used in the project pvr.mythtv: https://github.com/janbar/pvr.mythtv/blob/doityourself/src/demux.cpp , and see required PTS/DTS data are transfered to the player with each parsed frame: https://github.com/janbar/pvr.mythtv/blob/doityourself/src/demux.cpp#L539 .
